### ISSUE TITLE
File not found error on reload

### ISSUE THREAD

**Issue by AjithRamachandran** [metacall/core#150]
## 🐛 Bug Report

Error when trying to reload the python file.

logs:
```
λ load py main.py
Traceback (most recent call last):
  File "py_loader_impl_load_from_file_path", line 12, in load_from_path
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/gnu/store/s8q2rskbm5lzbf64l9h9i26j4mvx6ghr-metacall-0.4.9R/lib/main.py'

Traceback (most recent call last):
  File "py_loader_impl_load_from_file_path", line 12, in load_from_path
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/gnu/store/ibhpswbqd53w2rsdhaqn05lx2p61nilg-python-3.8.2R/lib/main.py'

Traceback (most recent call last):
  File "py_loader_impl_load_from_file_path", line 12, in load_from_path
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/gnu/store/q9rm8h9imazsq2c4qiv2yjpvlvliywqb-python-3.8.2/lib/python38.zip/main.py'

Traceback (most recent call last):
  File "py_loader_impl_load_from_file_path", line 12, in load_from_path
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/gnu/store/q9rm8h9imazsq2c4qiv2yjpvlvliywqb-python-3.8.2/lib/python3.8/main.py'

Traceback (most recent call last):
  File "py_loader_impl_load_from_file_path", line 12, in load_from_path
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/gnu/store/q9rm8h9imazsq2c4qiv2yjpvlvliywqb-python-3.8.2/lib/python3.8/lib-dynload/main.py'

Traceback (most recent call last):
  File "py_loader_impl_load_from_file_path", line 12, in load_from_path
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/gnu/store/q9rm8h9imazsq2c4qiv2yjpvlvliywqb-python-3.8.2/lib/python3.8/site-packages/main.py'

Script (main.py) load error in loader (py)
```

**Comment by viferga** [comment]
I could not reproduce your bug, neither there is enough information to reproduce it.

```sh
λ load py callback.py
Error when loading MetaCall Python Port: No module named 'metacall'
Traceback (most recent call last):
  File "py_loader_impl_load_from_file_path", line 12, in load_from_path
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/media/sf_metacall/source/ports/py_port/callback.py'

Script (callback.py) loaded correctly
λ inspect
runtime __metacall_host__
runtime py {
	module callback.py { 
		function callback_ruby(left, right)
		function callback_host(text)
		function hello_ruby(left, right)
		function hello_world(text)
	}
}
λ clear py callback.py
Script (callback.py) removed correctly
λ inspect
runtime __metacall_host__
runtime py
λ load py callback.py
Traceback (most recent call last):
  File "py_loader_impl_load_from_file_path", line 12, in load_from_path
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/media/sf_metacall/source/ports/py_port/callback.py'

Script (callback.py) loaded correctly
λ inspect
runtime __metacall_host__
runtime py {
	module callback.py { 
		function callback_ruby(left, right)
		function callback_host(text)
		function hello_ruby(left, right)
		function hello_world(text)
	}
}
λ 
```
