### ISSUE TITLE
Building on OSX fails

### ISSUE THREAD

**Issue by inimeseke** [metacall/core#223]
## 🐛 Bug Report

Building on OSX 10.14.6 fails due to SSL.
https://stackoverflow.com/a/42334357

Running
`cmake -DOPTION_BUILD_BACKTRACE=OFF -DOPTION_BUILD_TESTS=OFF -DOPTION_BUILD_LOADERS_PY=ON -DOPTION_BUILD_LOADERS_NODE=ON ..`
then 
`make -j4`

Results in this.

```
-- Configure NodeJS shared library
 <https://github.com/unicode-org/icu/releases/download/release-65-1/icu4c-65_1-src.zip>
 ** IOError [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)

Traceback (most recent call last):
  File "./configure", line 28, in <module>
    import configure
  File "/Users/mart/metacall/core/build/source/loaders/node_loader/sources/node-v12.18.3/configure.py", line 1710, in <module>
    configure_intl(output)
  File "/Users/mart/metacall/core/build/source/loaders/node_loader/sources/node-v12.18.3/configure.py", line 1550, in configure_intl
    nodedownload.unpack(icu_tarball, icu_tmp_path)
  File "tools/configure.d/nodedownload.py", line 73, in unpack
    if zipfile.is_zipfile(packedfile):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 175, in is_zipfile
    with open(filename, "rb") as fp:
TypeError: coercing to Unicode: need string or buffer, NoneType found
-- Build NodeJS shared library
make: *** out: No such file or directory.  Stop.
-- Install NodeJS shared library
Missing or stale config.gypi, please run ./configure
make: *** [config.gypi] Error 1
CMake Error at cmake/FindNodeJS.cmake:496 (message):
  NodeJS library not found and it could not be built from source
Call Stack (most recent call first):
  source/loaders/node_loader/CMakeLists.txt:10 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/mart/metacall/core/build/CMakeFiles/CMakeOutput.log".
```

### Possible Solution

Setting this in FindNodeJS.cmake seems to solve it

```
if("${CMAKE_BUILD_TYPE}" EQUAL "Debug")
				#execute_process(COMMAND sh -c "./configure --with-icu-source=${ICU_URL} --shared --debug" WORKING_DIRECTORY "${NodeJS_OUTPUT_PATH}")
				execute_process(COMMAND ${CMAKE_COMMAND} -E env PYTHONHTTPSVERIFY=0 sh -c "./configure --with-icu-source=${ICU_URL} --shared" WORKING_DIRECTORY "${NodeJS_OUTPUT_PATH}")
			else()
				execute_process(COMMAND sh -c "./configure --with-icu-source=${ICU_URL} --shared" WORKING_DIRECTORY "${NodeJS_OUTPUT_PATH}")
			endif()
```

**Comment by viferga** [comment]
Solved: https://github.com/metacall/core/commit/8830fe88cc7419893ab1a73ebde69b7c3340fe61
