### ISSUE TITLE
py_port test fails due to rs_loader linker bug

### ISSUE THREAD

**Issue by viferga** [metacall/core#331]
## 🐛 Bug Report

You can reproduce it by running `./docker-compose.sh test`. It does not happen outside docker, neither with sanitizers enabled, but it happens with  `./docker-compose.sh test-sanitizer` too.

```
 30/168 Test   #3: py_port ..........................................***Failed    8.53 sec
.....warning: field is never read: `constructor`
  --> /usr/local/metacall/build/scripts/metacall_class.rs:52:5
   |
52 |     constructor: Option<Constructor>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: field is never read: `attributes`
  --> /usr/local/metacall/build/scripts/metacall_class.rs:53:5
   |
53 |     attributes: Attributes,
   |     ^^^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `attr_setters`
  --> /usr/local/metacall/build/scripts/metacall_class.rs:54:5
   |
54 |     attr_setters: AttributeSetters,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `instance_methods`
  --> /usr/local/metacall/build/scripts/metacall_class.rs:55:5
   |
55 |     instance_methods: InstanceMethods,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: associated function is never used: `builder`
  --> /usr/local/metacall/build/scripts/metacall_class.rs:60:12
   |
60 |     pub fn builder<T: 'static>() -> ClassBuilder<T> {
   |            ^^^^^^^

warning: associated function is never used: `init`
  --> /usr/local/metacall/build/scripts/metacall_class.rs:64:12
   |
64 |     pub fn init(&self, fields: Vec<MetacallValue>) -> Instance {
   |            ^^^^

warning: associated function is never used: `call`
  --> /usr/local/metacall/build/scripts/metacall_class.rs:72:12
   |
72 |     pub fn call(&self, attr: &str, args: Vec<MetacallValue>) -> Result<MetacallValue> {
   |            ^^^^

warning: associated function is never used: `get_method`
  --> /usr/local/metacall/build/scripts/metacall_class.rs:81:8
   |
81 |     fn get_method(&self, name: &str) -> Option<InstanceMethod> {
   |        ^^^^^^^^^^

warning: field is never read: `class`
  --> /usr/local/metacall/build/scripts/metacall_class.rs:88:5
   |
88 |     class: Class,
   |     ^^^^^^^^^^^^

warning: associated function is never used: `new`
  --> /usr/local/metacall/build/scripts/metacall_class.rs:97:8
   |
97 |     fn new() -> Self {
   |        ^^^

warning: associated function is never used: `name`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:114:12
    |
114 |     pub fn name(mut self, name: &str) -> Self {
    |            ^^^^

warning: associated function is never used: `build`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:120:12
    |
120 |     pub fn build(self) -> Class {
    |            ^^^^^

warning: associated function is never used: `add_attribute_getter`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:124:12
    |
124 |     pub fn add_attribute_getter<F, R>(mut self, name: &'static str, f: F) -> Self
    |            ^^^^^^^^^^^^^^^^^^^^

warning: associated function is never used: `add_attribute_setter`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:134:12
    |
134 |     pub fn add_attribute_setter<F, Arg>(mut self, name: &'static str, f: F) -> Self
    |            ^^^^^^^^^^^^^^^^^^^^

warning: associated function is never used: `with_constructor`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:146:12
    |
146 |     pub fn with_constructor<F, Args>(f: F) -> Self
    |            ^^^^^^^^^^^^^^^^

warning: associated function is never used: `set_constructor`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:157:12
    |
157 |     pub fn set_constructor<F, Args>(mut self, f: F) -> Self
    |            ^^^^^^^^^^^^^^^

warning: associated function is never used: `add_method`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:167:12
    |
167 |     pub fn add_method<F, Args, R>(mut self, name: &'static str, f: F) -> Self
    |            ^^^^^^^^^^

warning: associated function is never used: `add_class_method`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:179:12
    |
179 |     pub fn add_class_method<F, Args, R>(mut self, name: &'static str, f: F) -> Self
    |            ^^^^^^^^^^^^^^^^

warning: field is never read: `inner`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:191:5
    |
191 |     inner: Arc<RefCell<dyn std::any::Any + Send + Sync>>,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: associated function is never used: `new`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:203:12
    |
203 |     pub fn new<T: Send + Sync + 'static>(instance: T) -> Self {
    |            ^^^

warning: associated function is never used: `instance_of`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:211:12
    |
211 |     pub fn instance_of(&self, class: &Class) -> bool {
    |            ^^^^^^^^^^^

warning: associated function is never used: `type_id`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:215:12
    |
215 |     pub fn type_id(&self) -> std::any::TypeId {
    |            ^^^^^^^

warning: associated function is never used: `name`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:220:12
    |
220 |     pub fn name<'a>(&self) -> &'a str {
    |            ^^^^

warning: associated function is never used: `get_attr`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:225:12
    |
225 |     pub fn get_attr(&self, name: &str, class: &Class) -> Result<MetacallValue> {
    |            ^^^^^^^^

warning: associated function is never used: `set_attr`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:233:12
    |
233 |     pub fn set_attr(&mut self, name: &str, value: MetacallValue, class: &Class) {
    |            ^^^^^^^^

warning: associated function is never used: `borrow`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:242:12
    |
242 |     pub fn borrow(&self) -> Ref<dyn std::any::Any + Send + Sync> {
    |            ^^^^^^

warning: associated function is never used: `borrow_mut`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:246:12
    |
246 |     pub fn borrow_mut(&self) -> RefMut<dyn std::any::Any + Send + Sync> {
    |            ^^^^^^^^^^

warning: associated function is never used: `call`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:250:12
    |
250 |     pub fn call(
    |            ^^^^

warning: function is never used: `join`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:325:4
    |
325 | fn join<A, B>(left: Result<A>, right: Result<B>) -> Result<(A, B)> {
    |    ^^^^

warning: associated function is never used: `new`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:336:12
    |
336 |     pub fn new<Args, F>(f: F) -> Self
    |            ^^^

warning: associated function is never used: `invoke`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:347:12
    |
347 |     pub fn invoke(&self, args: Vec<MetacallValue>) -> Result<Instance> {
    |            ^^^^^^

warning: associated function is never used: `new`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:355:12
    |
355 |     pub fn new<T, F, R>(f: F) -> Self
    |            ^^^

warning: associated function is never used: `invoke`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:370:12
    |
370 |     pub fn invoke(&self, receiver: &Instance) -> Result<MetacallValue> {
    |            ^^^^^^

warning: associated function is never used: `new`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:378:12
    |
378 |     pub fn new<T, F, Arg>(f: F) -> Self
    |            ^^^

warning: associated function is never used: `invoke`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:393:12
    |
393 |     pub fn invoke(&self, value: MetacallValue, receiver: &mut Instance) {
    |            ^^^^^^

warning: associated function is never used: `new`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:402:12
    |
402 |     pub fn new<T, F, Args>(f: F) -> Self
    |            ^^^

warning: associated function is never used: `invoke`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:424:12
    |
424 |     pub fn invoke(&self, receiver: &Instance, args: Vec<MetacallValue>) -> Result<MetacallValue> {
    |            ^^^^^^

warning: associated function is never used: `new`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:433:12
    |
433 |     pub fn new<F, Args>(f: F) -> Self
    |            ^^^

warning: associated function is never used: `invoke`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:447:12
    |
447 |     pub fn invoke(&self, args: Vec<MetacallValue>) -> Result<MetacallValue> {
    |            ^^^^^^

warning: associated function is never used: `invoke`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:470:12
    |
470 |     pub fn invoke(&self, args: Vec<MetacallValue>) -> Result<MetacallValue> {
    |            ^^^^^^

warning: unused `std::result::Result` that must be used
  --> /usr/local/metacall/build/scripts/basic.rs:21:5
   |
21 |     f.write(b"Hello metacall");
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_must_use)]` on by default
   = note: this `Result` may be an `Err` variant, which should be handled

error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-Wl,--version-script=/tmp/rustchT84ZM/list" "-m64" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.0.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.1.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.10.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.11.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.12.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.13.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.14.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.15.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.2.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.3.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.4.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.5.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.6.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.7.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.8.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.9.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.2ep5rm9qie5mibsg.rcgu.o" "-Wl,--as-needed" "-L" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-13e2ae73269b4206.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-3d4ff53e7005b4dd.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-54bcdfc29d659c8a.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-4534cde42d1275da.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-a2bd8b0ea7c9b00d.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-8881dc3bb3f10f3b.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-3fd242e18fdd0c36.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-3a798fed05fab799.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-80d3100602c910ea.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-1dccce5a21675f27.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-f64377ecebdde207.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-c7653eb7fe07b9c8.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-36839fa9267107c9.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-8aa1cded26ac715b.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-f48e57d6d73020ee.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-e95d805e5aecd8ef.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-2a6a2797f7a73818.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-0e3656b1fda5fd7b.rlib" "-Wl,--end-group" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-18115510f759732e.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/usr/local/metacall/build/scripts/wrapped_basic.so" "-Wl,--gc-sections" "-shared" "-Wl,-zrelro,-znow" "-Wl,-O1" "-nodefaultlibs"
  = note: /usr/bin/ld: can not read symbols: file truncated
          /usr/bin/ld: can not read symbols: file truncated
          /usr/bin/ld: failed to set dynamic section sizes: file truncated
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error; 41 warnings emitted



ErrorReported

warning: field is never read: `constructor`
  --> /usr/local/metacall/build/scripts/metacall_class.rs:52:5
   |
52 |     constructor: Option<Constructor>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: field is never read: `attributes`
  --> /usr/local/metacall/build/scripts/metacall_class.rs:53:5
   |
53 |     attributes: Attributes,
   |     ^^^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `attr_setters`
  --> /usr/local/metacall/build/scripts/metacall_class.rs:54:5
   |
54 |     attr_setters: AttributeSetters,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `instance_methods`
  --> /usr/local/metacall/build/scripts/metacall_class.rs:55:5
   |
55 |     instance_methods: InstanceMethods,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: associated function is never used: `builder`
  --> /usr/local/metacall/build/scripts/metacall_class.rs:60:12
   |
60 |     pub fn builder<T: 'static>() -> ClassBuilder<T> {
   |            ^^^^^^^

warning: associated function is never used: `init`
  --> /usr/local/metacall/build/scripts/metacall_class.rs:64:12
   |
64 |     pub fn init(&self, fields: Vec<MetacallValue>) -> Instance {
   |            ^^^^

warning: associated function is never used: `call`
  --> /usr/local/metacall/build/scripts/metacall_class.rs:72:12
   |
72 |     pub fn call(&self, attr: &str, args: Vec<MetacallValue>) -> Result<MetacallValue> {
   |            ^^^^

warning: associated function is never used: `get_method`
  --> /usr/local/metacall/build/scripts/metacall_class.rs:81:8
   |
81 |     fn get_method(&self, name: &str) -> Option<InstanceMethod> {
   |        ^^^^^^^^^^

warning: field is never read: `class`
  --> /usr/local/metacall/build/scripts/metacall_class.rs:88:5
   |
88 |     class: Class,
   |     ^^^^^^^^^^^^

warning: associated function is never used: `new`
  --> /usr/local/metacall/build/scripts/metacall_class.rs:97:8
   |
97 |     fn new() -> Self {
   |        ^^^

warning: associated function is never used: `name`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:114:12
    |
114 |     pub fn name(mut self, name: &str) -> Self {
    |            ^^^^

warning: associated function is never used: `build`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:120:12
    |
120 |     pub fn build(self) -> Class {
    |            ^^^^^

warning: associated function is never used: `add_attribute_getter`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:124:12
    |
124 |     pub fn add_attribute_getter<F, R>(mut self, name: &'static str, f: F) -> Self
    |            ^^^^^^^^^^^^^^^^^^^^

warning: associated function is never used: `add_attribute_setter`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:134:12
    |
134 |     pub fn add_attribute_setter<F, Arg>(mut self, name: &'static str, f: F) -> Self
    |            ^^^^^^^^^^^^^^^^^^^^

warning: associated function is never used: `with_constructor`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:146:12
    |
146 |     pub fn with_constructor<F, Args>(f: F) -> Self
    |            ^^^^^^^^^^^^^^^^

warning: associated function is never used: `set_constructor`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:157:12
    |
157 |     pub fn set_constructor<F, Args>(mut self, f: F) -> Self
    |            ^^^^^^^^^^^^^^^

warning: associated function is never used: `add_method`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:167:12
    |
167 |     pub fn add_method<F, Args, R>(mut self, name: &'static str, f: F) -> Self
    |            ^^^^^^^^^^

warning: associated function is never used: `add_class_method`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:179:12
    |
179 |     pub fn add_class_method<F, Args, R>(mut self, name: &'static str, f: F) -> Self
    |            ^^^^^^^^^^^^^^^^

warning: field is never read: `inner`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:191:5
    |
191 |     inner: Arc<RefCell<dyn std::any::Any + Send + Sync>>,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: associated function is never used: `new`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:203:12
    |
203 |     pub fn new<T: Send + Sync + 'static>(instance: T) -> Self {
    |            ^^^

warning: associated function is never used: `instance_of`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:211:12
    |
211 |     pub fn instance_of(&self, class: &Class) -> bool {
    |            ^^^^^^^^^^^

warning: associated function is never used: `type_id`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:215:12
    |
215 |     pub fn type_id(&self) -> std::any::TypeId {
    |            ^^^^^^^

warning: associated function is never used: `name`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:220:12
    |
220 |     pub fn name<'a>(&self) -> &'a str {
    |            ^^^^

warning: associated function is never used: `get_attr`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:225:12
    |
225 |     pub fn get_attr(&self, name: &str, class: &Class) -> Result<MetacallValue> {
    |            ^^^^^^^^

warning: associated function is never used: `set_attr`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:233:12
    |
233 |     pub fn set_attr(&mut self, name: &str, value: MetacallValue, class: &Class) {
    |            ^^^^^^^^

warning: associated function is never used: `borrow`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:242:12
    |
242 |     pub fn borrow(&self) -> Ref<dyn std::any::Any + Send + Sync> {
    |            ^^^^^^

warning: associated function is never used: `borrow_mut`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:246:12
    |
246 |     pub fn borrow_mut(&self) -> RefMut<dyn std::any::Any + Send + Sync> {
    |            ^^^^^^^^^^

warning: associated function is never used: `call`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:250:12
    |
250 |     pub fn call(
    |            ^^^^

warning: function is never used: `join`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:325:4
    |
325 | fn join<A, B>(left: Result<A>, right: Result<B>) -> Result<(A, B)> {
    |    ^^^^

warning: associated function is never used: `new`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:336:12
    |
336 |     pub fn new<Args, F>(f: F) -> Self
    |            ^^^

warning: associated function is never used: `invoke`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:347:12
    |
347 |     pub fn invoke(&self, args: Vec<MetacallValue>) -> Result<Instance> {
    |            ^^^^^^

warning: associated function is never used: `new`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:355:12
    |
355 |     pub fn new<T, F, R>(f: F) -> Self
    |            ^^^

warning: associated function is never used: `invoke`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:370:12
    |
370 |     pub fn invoke(&self, receiver: &Instance) -> Result<MetacallValue> {
    |            ^^^^^^

warning: associated function is never used: `new`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:378:12
    |
378 |     pub fn new<T, F, Arg>(f: F) -> Self
    |            ^^^

warning: associated function is never used: `invoke`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:393:12
    |
393 |     pub fn invoke(&self, value: MetacallValue, receiver: &mut Instance) {
    |            ^^^^^^

warning: associated function is never used: `new`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:402:12
    |
402 |     pub fn new<T, F, Args>(f: F) -> Self
    |            ^^^

warning: associated function is never used: `invoke`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:424:12
    |
424 |     pub fn invoke(&self, receiver: &Instance, args: Vec<MetacallValue>) -> Result<MetacallValue> {
    |            ^^^^^^

warning: associated function is never used: `new`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:433:12
    |
433 |     pub fn new<F, Args>(f: F) -> Self
    |            ^^^

warning: associated function is never used: `invoke`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:447:12
    |
447 |     pub fn invoke(&self, args: Vec<MetacallValue>) -> Result<MetacallValue> {
    |            ^^^^^^

warning: associated function is never used: `invoke`
   --> /usr/local/metacall/build/scripts/metacall_class.rs:470:12
    |
470 |     pub fn invoke(&self, args: Vec<MetacallValue>) -> Result<MetacallValue> {
    |            ^^^^^^

warning: unused `std::result::Result` that must be used
  --> /usr/local/metacall/build/scripts/basic.rs:21:5
   |
21 |     f.write(b"Hello metacall");
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_must_use)]` on by default
   = note: this `Result` may be an `Err` variant, which should be handled

error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-Wl,--version-script=/tmp/rustchT84ZM/list" "-m64" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.0.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.1.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.10.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.11.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.12.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.13.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.14.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.15.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.2.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.3.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.4.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.5.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.6.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.7.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.8.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.wrapped_basic.542f1037-cgu.9.rcgu.o" "/usr/local/metacall/build/scripts/wrapped_basic.2ep5rm9qie5mibsg.rcgu.o" "-Wl,--as-needed" "-L" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-13e2ae73269b4206.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-3d4ff53e7005b4dd.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-54bcdfc29d659c8a.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-4534cde42d1275da.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-a2bd8b0ea7c9b00d.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-8881dc3bb3f10f3b.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-3fd242e18fdd0c36.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-3a798fed05fab799.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-80d3100602c910ea.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-1dccce5a21675f27.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-f64377ecebdde207.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-c7653eb7fe07b9c8.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-36839fa9267107c9.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-8aa1cded26ac715b.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-f48e57d6d73020ee.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-e95d805e5aecd8ef.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-2a6a2797f7a73818.rlib" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-0e3656b1fda5fd7b.rlib" "-Wl,--end-group" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-18115510f759732e.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/root/.rustup/toolchains/nightly-2021-12-04-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/usr/local/metacall/build/scripts/wrapped_basic.so" "-Wl,--gc-sections" "-shared" "-Wl,-zrelro,-znow" "-Wl,-O1" "-nodefaultlibs"
  = note: /usr/bin/ld: can not read symbols: file truncated
          /usr/bin/ld: can not read symbols: file truncated
          /usr/bin/ld: failed to set dynamic section sizes: file truncated
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error; 41 warnings emitted


E
======================================================================
ERROR: test_rust (test_simple.py_port_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/metacall/source/ports/py_port/test/test_simple.py", line 101, in test_rust
    from basic.rs import add, add_float, string_len, new_string
  File "/usr/local/metacall/source/ports/py_port/metacall/api.py", line 251, in __metacall_import__
    raise ImportException(f'MetaCall could not import: {name}')
ModuleNotFoundError: MetaCall could not import: basic.rs

----------------------------------------------------------------------
Ran 6 tests in 1.900s

FAILED (errors=1)
```

**Comment by MediosZ** [comment]
I am on it.
